import random
import json

data = [
    {"name": "Ginger", "price": 64},
    {"name": "Blueberry", "price": 42},
    {"name": "Pineapple", "price": 90},
    {"name": "Onion", "price": 1},
    {"name": "Apple", "price": 78},
    {"name": "Strawberry", "price": 81},
    {"name": "Eggplant", "price": 12},
    {"name": "Banana", "price": 79},
    {"name": "Spinach", "price": 73},
    {"name": "Potato", "price": 2},
    {"name": "Orange", "price": 61},
    {"name": "Sweet Potato", "price": 21},
    {"name": "Strawberry", "price": 2},
    {"name": "Turnip", "price": 67},
    {"name": "Turnip", "price": 96},
    {"name": "Mango", "price": 97},
    {"name": "Pumpkin", "price": 1},
    {"name": "Kiwi", "price": 20},
    {"name": "Mango", "price": 39},
    {"name": "Broccoli", "price": 10},
    {"name": "Blackberry", "price": 14},
    {"name": "Tomato", "price": 29},
    {"name": "Mango", "price": 66},
    {"name": "Garlic", "price": 54},
    {"name": "Brussels Sprout", "price": 17},
    {"name": "Blackberry", "price": 37},
    {"name": "Blackberry", "price": 30},
    {"name": "Lettuce", "price": 53},
    {"name": "Blackberry", "price": 36},
    {"name": "Sweet Potato", "price": 34},
    {"name": "Tomato", "price": 89},
    {"name": "Spinach", "price": 45},
    {"name": "Pumpkin", "price": 68},
    {"name": "Kiwi", "price": 41},
    {"name": "Potato", "price": 65},
    {"name": "Asparagus", "price": 45},
    {"name": "Potato", "price": 14},
    {"name": "Cherry", "price": 96},
    {"name": "Onion", "price": 84},
    {"name": "Honeydew", "price": 56},
    {"name": "Chili Pepper", "price": 33},
    {"name": "Grapes", "price": 91},
    {"name": "Blackberry", "price": 18},
    {"name": "Honeydew", "price": 50},
    {"name": "Lemon", "price": 6},
    {"name": "Cucumber", "price": 47},
    {"name": "Cabbage", "price": 55},
    {"name": "Carrot", "price": 77},
    {"name": "Peach", "price": 88},
    {"name": "Plum", "price": 25},
    {"name": "Watermelon", "price": 99},
    {"name": "Cantaloupe", "price": 23},
    {"name": "Raspberry", "price": 62},
    {"name": "Blueberry", "price": 43},
    {"name": "Avocado", "price": 74},
    {"name": "Cauliflower", "price": 85},
    {"name": "Zucchini", "price": 31},
    {"name": "Squash", "price": 52},
    {"name": "Bell Pepper", "price": 19},
    {"name": "Radish", "price": 27},
    {"name": "Beetroot", "price": 49},
    {"name": "Celery", "price": 22},
    {"name": "Artichoke", "price": 35},
    {"name": "Asparagus", "price": 46},
    {"name": "Brussels Sprout", "price": 17},
    {"name": "Blackberry", "price": 37},
    {"name": "Blackberry", "price": 30},
    {"name": "Lettuce", "price": 53},
    {"name": "Blackberry", "price": 36},
    {"name": "Sweet Potato", "price": 34},
    {"name": "Tomato", "price": 89},
    {"name": "Spinach", "price": 45},
    {"name": "Pumpkin", "price": 68},
    {"name": "Kiwi", "price": 41},
    {"name": "Potato", "price": 65},
    {"name": "Asparagus", "price": 45},
    {"name": "Potato", "price": 14},
    {"name": "Cherry", "price": 96},
    {"name": "Onion", "price": 84},
    {"name": "Honeydew", "price": 56},
    {"name": "Chili Pepper", "price": 33},
    {"name": "Grapes", "price": 91},
    {"name": "Blackberry", "price": 18},
    {"name": "Honeydew", "price": 50},
    {"name": "Lemon", "price": 6},
    {"name": "Cucumber", "price": 47},
    {"name": "Cabbage", "price": 55},
    {"name": "Carrot", "price": 77},
    {"name": "Peach", "price": 88},
    {"name": "Plum", "price": 25},
    {"name": "Watermelon", "price": 99},
    {"name": "Cantaloupe", "price": 23},
    {"name": "Raspberry", "price": 62},
    {"name": "Blueberry", "price": 43},
    {"name": "Avocado", "price": 74},
    {"name": "Cauliflower", "price": 85},
    {"name": "Choco", "price": 95},
    {"name": "Berry", "price": 90},
    {"name": "Chilly", "price": 45},
    {"name": "Potato", "price": 30},
    {"name": "Tomato", "price": 43}
]

shop_names = [
    'Fresh Harvest Market',
    'Green Valley Grocers',
    'Nature\'s Basket',
    'Orchard Fresh',
    'Veggie Delight',
    'Fruitful Finds',
    'Garden Goods',
    'Farm Fresh Produce',
    'Healthy Harvest',
    'Organic Oasis',
    'Pure Produce',
    'Veggie Haven',
    'Fruit Fiesta',
    'Green Grocers',
    'Fresh Fields Market'
]

for x in data:
    x['available_quantity'] = random.randint(0,50)
    x['shop'] = shop_names[random.randint(0,14)]


with open('data.json', 'w') as f:
    json.dump(data, f)